sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: HuUsH02I4KlfGh49T0Y7WM3wn6z6deSbv1rof8GWdCnizPRXVz7vCJWT9bL6y7UmgS3Uh7cbOupcvsh/keWWLc5dHPbepctleFAT/rqqdKkh0iB4PR7h3B9MfgcNxjKAW7ybST4263ejbug/JrkEQZc9hezscchsOWZrqX+fnS5MUVo/niSGw90STv0s6r0hpO9b2mvZMVzovWmscN2PAr3cP8fWY8c68po59l6zbj3oIzv+Gen8hMf5PO/gCOwxq+BIjWhyXjhqw9ESvfdXftrw8vF6cdQuvMfgmyRk9vnoHNn4PrGmJQoMp9YzivF4G06J5b3BVcv6XT7mRh8tqkuqqU7k8xrlECF6hihEAZhE8ZlsWAb8l1Fhh90TCUpsSkMpnEXWvhcmqlc1FajPIO4Xg+xkuMIg1fKsicroQEVWZAaqQhvQkrpoPPj05uqFuMPQ+vDaV+0jv+gw/P2ca3ntps0OOrql6RH6SzQGLH569Wd42owC1QJ06H8DimRESzSilv9/S7Ud7SRtLePfaJoPLMhxueU4zmPCAivIwYZX+7Tobcirq8k5MC0l6sHHI1x4PVzZc4XLSI3ve0gqk5fdzqMeBPvp79vlYG7I5IImeVVhkV/5s0Q+VMPOqTuAGfUkVyRccq1LEGBV50A0gPJl35EXR+hJ4nDAndqIEIE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Mrs.-Skagg-s-Husbands-and-Other-Stories_2597
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy